### ISSUE TITLE
multiple zone types per region

### ISSUE THREAD

**Issue by mxndrwgrdnr** [ual/PILATES#18]
@jdcaicedo251 do you know what will happen [here](https://github.com/ual/PILATES/blob/master/pilates/utils/geog.py#L234-L246) if I run for Bay Area on the BEAM taz-based skims, and then run on the new block group-based skims once we get them? Will the block-group based run attempt to read the geoid_to_taz.csv file that was created by the taz-based runs? That would be a problem.

Do you think it makes to sense to have the mapping file names be more descriptive to avoid this scenario? e.g. "block_to_taz.csv", "block_group_to_taz.csv"? The former would get created when dealing with taz-based skims, and the latter would get created when dealing with census geom-based skims. What do you think?

**Comment by jdcaicedo251** [comment]
Yes, the preprocessing generates only one mapping file that depends on the zone type. If the same area gets run with another zone type it would generate an error. Let me create different mapping files for each zone type to avoid having this issue.

**Comment by jdcaicedo251** [comment]
Issue solve #20
